title: Bhargav Dasari # your name (or website title) here
logo: "/images/github-profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist 
  <br><br>
  My interests so far lie in software development, focusing on Machine Learning infrastructure for Computer Vision and Natural Language Processing. 
  <br><br>
  <a href="https://www.linkedin.com/in/sai-bhargav-dasari/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
